# Generated by Django 6.0.3 on 2026-03-18 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0003_dataset_file_size'),
        ('issues', '0008_remove_issue_detected_by_remove_issue_is_resolved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('FILL_NA', 'Fill missing values'), ('DROP_ROWS', 'Drop rows'), ('DROP_DUPLICATES', 'Drop duplicates'), ('CLIP_OUTLIERS', 'Clip outliers'), ('REMOVE_OUTLIERS', 'Remove outliers'), ('CAST_COLUMN', 'Cast column type'), ('STANDARDIZE_FORMAT', 'Standardize format'), ('REPLACE_VALUES', 'Replace values'), ('STRIP_WHITESPACE', 'Strip whitespace'), ('FIX_ENCODING', 'Fix encoding'), ('STANDARDIZE_CASE', 'Standardize case'), ('RENAME_COLUMN', 'Rename column')], max_length=32)),
                ('column_name', models.CharField(blank=True, default='', max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('rows_affected', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('FAILED', 'Failed'), ('REVERTED', 'Reverted')], default='PENDING', max_length=16)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_ops', to='datasets.dataset')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_ops', to='issues.issue')),
            ],
            options={
                'verbose_name': 'Cleaning Operation',
                'verbose_name_plural': 'Cleaning Operations',
                'ordering': ['-created_at'],
            },
        ),
    ]
