# Generated by Django 5.2.1 on 2026-03-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='column_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='suggested_fix',
            field=models.TextField(blank=True, default=''),
        ),
    ]
