# Generated by Django 5.2.1 on 2026-03-01 07:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, help_text='e.g. Sales, Marketing, Research', max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('color_code', models.CharField(default='#4F46E5', help_text='HEX color for UI cards', max_length=7)),
                ('thumbnail', models.URLField(blank=True, help_text='Cover image URL', null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(help_text='The individual owner of this project.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-is_favorite', '-last_accessed_at'],
            },
        ),
    ]
