# Generated by Django 5.2.1 on 2026-03-02 09:23

import django.db.models.deletion
import datasets.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="datasets/%Y/%m/%d/",
                        validators=[datasets.validators.validate_file_size_and_type],
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file_format", models.CharField(blank=True, max_length=10)),
                ("row_count", models.IntegerField(blank=True, null=True)),
                ("column_count", models.IntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
