# Generated by Django 5.2.1 on 2026-03-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectdataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdataset',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
