# Generated by Django 5.2.1 on 2026-03-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectdataset_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectDataset',
        ),
    ]
