# Generated by Django 5.2.1 on 2026-02-11 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='First name can only contain letters, hyphens, apostrophes, and spaces.', regex="^[a-zA-ZÀ-ÿ'\\- ]+$"), django.core.validators.MinLengthValidator(2, message='First name must be at least 2 characters long.')]),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Full name can only contain letters and spaces.', regex='^[a-zA-ZÀ-ÿ ]+$'), django.core.validators.MinLengthValidator(10, message='Full name must be at least 10 characters long.'), django.core.validators.MaxLengthValidator(255)]),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Last name can only contain letters, hyphens, apostrophes, and spaces.', regex="^[a-zA-ZÀ-ÿ'\\- ]+$"), django.core.validators.MinLengthValidator(2, message='Last name must be at least 2 characters long.')]),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, numbers, dots, underscores, and hyphens.', regex='^[a-zA-Z0-9._-]+$'), django.core.validators.MinLengthValidator(3, message='Username must be at least 3 characters long.')]),
        ),
    ]
