# Generated by Django 5.2.10 on 2026-01-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userfile_user_alter_userfile_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
