from dj_rest_auth.serializers import UserDetailsSerializer
from dj_rest_auth.registration.serializers import RegisterSerializer
from rest_framework import serializers
from allauth.account.adapter import get_adapter
from allauth.account.utils import setup_user_email
from django.contrib.auth import get_user_model

User = get_user_model()

def _email_already_exists(email):
    """Return True if a user with this email already exists (verified or not)."""
    return User.objects.filter(email__iexact=email).exists()


class CustomRegisterSerializer(RegisterSerializer):
    """
    Single-password registration: email + password (+ optional first_name/last_name).
    Username is auto-generated by CustomAccountAdapter.
    """

    username = None   # auto-generated in adapter
    password1 = None  # replaced by single `password` field below
    password2 = None  # confirmation field removed

    password = serializers.CharField(write_only=True)
    first_name = serializers.CharField(required=False, allow_blank=True)
    last_name = serializers.CharField(required=False, allow_blank=True)

    def validate_email(self, email):
        email = get_adapter().clean_email(email)
        if _email_already_exists(email):
            raise serializers.ValidationError("A user with this email already exists.")
        return email

    def validate_password(self, value):
        return get_adapter().clean_password(value)

    def validate(self, data):
        return data

    def get_cleaned_data(self):
        return {
            "password1": self.validated_data.get("password", ""),
            "email": self.validated_data.get("email", ""),
            "first_name": self.validated_data.get("first_name", ""),
            "last_name": self.validated_data.get("last_name", ""),
        }

    def save(self, request):
        adapter = get_adapter()
        user = adapter.new_user(request)
        self.cleaned_data = self.get_cleaned_data()
        user = adapter.save_user(request, user, self, commit=False)
        try:
            adapter.clean_password(self.cleaned_data["password1"], user=user)
        except Exception as exc:
            raise serializers.ValidationError(
                detail=serializers.as_serializer_error(exc)
            )
        user.save()
        self.custom_signup(request, user)
        setup_user_email(request, user, [])
        return user


class CustomUserDetailsSerializer(UserDetailsSerializer):
    """
    Extends dj-rest-auth's UserDetailsSerializer to return all
    AuthUser fields on login, registration, and GET /auth/user/.
    """

    class Meta(UserDetailsSerializer.Meta):
        model = User
        fields = (
            "id",
            "email",
            "username",
            "first_name",
            "last_name",
            "full_name",
            "profile_picture",
            "email_verified",
            "is_staff",
            "is_active",
            "date_joined",
            "last_login",
        )
        read_only_fields = (
            "id",
            "email",
            "email_verified",
            "date_joined",
            "last_login",
        )
