import pyotp

from dj_rest_auth.serializers import UserDetailsSerializer
from dj_rest_auth.registration.serializers import RegisterSerializer
from rest_framework import serializers
from allauth.account.adapter import get_adapter
from allauth.account.utils import setup_user_email
from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator

from .models import UserSession

User = get_user_model()


# ── Registration ─────────────────────────────────────────────────────────────

class CustomRegisterSerializer(RegisterSerializer):
    """
    Single-password registration: email + password (+ optional first_name/last_name).
    Username is auto-generated by CustomAccountAdapter.
    """

    username = None   # auto-generated in adapter
    password1 = None  # replaced by single `password` field below
    password2 = None  # confirmation field removed

    password = serializers.CharField(write_only=True)
    first_name = serializers.CharField(required=False, allow_blank=True)
    last_name = serializers.CharField(required=False, allow_blank=True)

    def validate_email(self, email):
        email = get_adapter().clean_email(email)
        if User.objects.filter(email__iexact=email).exists():
            raise serializers.ValidationError("A user with this email already exists.")
        return email

    def validate_password(self, value):
        return get_adapter().clean_password(value)

    def get_cleaned_data(self):
        return {
            "password1": self.validated_data.get("password", ""),
            "email": self.validated_data.get("email", ""),
            "first_name": self.validated_data.get("first_name", ""),
            "last_name": self.validated_data.get("last_name", ""),
        }

    def save(self, request):
        adapter = get_adapter()
        user = adapter.new_user(request)
        self.cleaned_data = self.get_cleaned_data()
        user = adapter.save_user(request, user, self, commit=False)
        try:
            adapter.clean_password(self.cleaned_data["password1"], user=user)
        except Exception as exc:
            raise serializers.ValidationError(
                detail=serializers.as_serializer_error(exc)
            )
        user.save()
        self.custom_signup(request, user)
        setup_user_email(request, user, [])
        return user


# ── User profile ─────────────────────────────────────────────────────────────

class CustomUserDetailsSerializer(UserDetailsSerializer):
    """
    Returned on login, registration, and GET/PATCH /auth/user/.
    Only first_name, last_name, and full_name are writable.
    """

    class Meta(UserDetailsSerializer.Meta):
        model = User
        fields = (
            "id",
            "email",
            "username",
            "first_name",
            "last_name",
            "full_name",
            "profile_picture",
            "email_verified",
            "is_staff",
            "is_active",
            "date_joined",
            "last_login",
        )
        read_only_fields = (
            "id",
            "email",
            "username",
            "profile_picture",
            "email_verified",
            "is_staff",
            "is_active",
            "date_joined",
            "last_login",
        )


# ── Sessions ─────────────────────────────────────────────────────────────────

class UserSessionSerializer(serializers.ModelSerializer):
    class Meta:
        model = UserSession
        fields = ("id", "device", "browser", "ip_address", "created_at", "last_active")
        read_only_fields = fields


# ── 2FA ──────────────────────────────────────────────────────────────────────

_DIGITS_ONLY = RegexValidator(r'^\d{6}$', 'Code must be exactly 6 digits.')


class TOTPEnableSerializer(serializers.Serializer):
    code = serializers.CharField(min_length=6, max_length=6, validators=[_DIGITS_ONLY])

    def validate_code(self, value):
        user = self.context["request"].user
        if user.totp_enabled:
            raise serializers.ValidationError("2FA is already enabled.")
        if not user.totp_secret:
            raise serializers.ValidationError(
                "Run GET /auth/2fa/setup/ first to generate a secret."
            )
        totp = pyotp.TOTP(user.totp_secret)
        if not totp.verify(value, valid_window=1):
            raise serializers.ValidationError("Invalid or expired code.")
        return value


class TOTPDisableSerializer(serializers.Serializer):
    code = serializers.CharField(min_length=6, max_length=6, validators=[_DIGITS_ONLY])
    password = serializers.CharField(write_only=True)

    def validate(self, data):
        user = self.context["request"].user
        if not user.totp_enabled:
            raise serializers.ValidationError("2FA is not enabled on this account.")
        if not user.check_password(data["password"]):
            raise serializers.ValidationError({"password": "Incorrect password."})
        totp = pyotp.TOTP(user.totp_secret)
        if not totp.verify(data["code"], valid_window=1):
            raise serializers.ValidationError({"code": "Invalid or expired code."})
        return data


class TOTPVerifyLoginSerializer(serializers.Serializer):
    totp_token = serializers.CharField()
    code = serializers.CharField(min_length=6, max_length=6, validators=[_DIGITS_ONLY])
