# Generated by Django 5.2.1 on 2026-03-16 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_authgrouppermissions_authusergroups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid email address.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(default='user1', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can only contain letters, numbers, dots, underscores, and hyphens.', regex='^[a-zA-Z0-9._-]+$'), django.core.validators.MinLengthValidator(3, message='Username must be at least 3 characters long.')]),
            preserve_default=False,
        ),
    ]
