# Generated by Django 5.2.1 on 2026-03-17 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('MISSING_VALUE', 'Missing Value'), ('DUPLICATE', 'Duplicate Row'), ('OUTLIER', 'Outlier'), ('SEMANTIC_ERROR', 'Semantic Error'), ('TYPE_MISMATCH', 'Type Mismatch')], max_length=50)),
                ('column_name', models.CharField(blank=True, max_length=255, null=True)),
                ('row_index', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('suggested_fix', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='datasets.dataset')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['-detected_at'],
            },
        ),
    ]
