# Generated by Django 6.0.3 on 2026-03-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_detected_by_affected_rows_is_user_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='detected_by',
            field=models.CharField(default='PANDAS', max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='severity',
            field=models.CharField(default='LOW', max_length=10),
        ),
    ]
