# Generated by Django 6.0.3 on 2026-03-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_issue_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('MISSING_VALUE', 'Missing Value'), ('DUPLICATE', 'Duplicate Row'), ('OUTLIER', 'Outlier'), ('SEMANTIC_ERROR', 'Semantic Error'), ('DATA_TYPE', 'Data Type'), ('INCONSISTENT_FORMATTING', 'Inconsistent Formatting'), ('INVALID_VALUE', 'Invalid Value'), ('WHITESPACE_ISSUE', 'Whitespace Issue'), ('SPECIAL_CHAR_ENCODING', 'Special Characters & Encoding'), ('INCONSISTENT_NAMING', 'Inconsistent Naming'), ('LOGICAL_INCONSISTENCY', 'Logical Inconsistency')], max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10),
        ),
    ]
