# Generated by Django 6.0.3 on 2026-03-18 07:32

from django.db import migrations


def map_type_mismatch_to_data_type(apps, schema_editor):
    Issue = apps.get_model("issues", "Issue")
    Issue.objects.filter(issue_type="TYPE_MISMATCH").update(issue_type="DATA_TYPE")


def noop_reverse(apps, schema_editor):
    # Intentional no-op: this forward migration normalizes legacy values.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_alter_issue_issue_type_alter_issue_severity'),
    ]

    operations = [
        migrations.RunPython(map_type_mismatch_to_data_type, noop_reverse),
    ]
