# Generated by Django 6.0.3 on 2026-03-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_map_type_mismatch_to_data_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='detected_by',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_user_modified',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='severity',
        ),
    ]
